blank_issues_enabled: true
contact_links:
  - name: Team Discussion
    url: https://github.com/sunnypatell/hackhive-2026/discussions
    about: Use Discussions for general questions or brainstorming
